# IA Xente Fraude detection MODEL

In [4]:
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder

In [5]:

Xente_Variable_Definitions_path = 'Xente_Variable_Definitions.csv'

Xente_Variable_Definitions_data = pd.read_csv(Xente_Variable_Definitions_path) 

Xente_Variable_Definitions_data

             Column Name                                         Definition
0          TransactionId         Unique �transaction identifier on platform
1                BatchId  Unique number assigned to a batch of transacti...
2              AccountId  Unique number identifying the customer on plat...
3         SubscriptionId  Unique number identifying the customer subscri...
4             CustomerId              Unique identifier attached to Account
5           CurrencyCode                                   Country currency
6            CountryCode             Numerical geographical code of country
7             ProviderId                   Source provider of Item �bought.
8              ProductId                            Item name being bought.
9        ProductCategory  ProductIds are organized into these broader pr...
10             ChannelId  Identifies if customer used web,Android, IOS, ...
11                Amount  Value of the transaction. Positive for debits ...
12                 Value                       Absolute value of the amount
13  TransactionStartTime                             Transaction start time
14       PricingStrategy  Category of Xente's pricing structure for merc...
15           FraudResult         Fraud status of transaction 1 -yes or 0-No

In [6]:
training_path = 'training.csv'

training_data = pd.read_csv(training_path) 

training_data.head()

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime,PricingStrategy,FraudResult
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z,2,0
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z,2,0
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z,2,0
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z,2,0
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z,2,0

In [7]:
y = training_data.FraudResult

In [8]:
features = [ f for f in Xente_Variable_Definitions_data['Column Name']]
features = features[0:14] #otherwise we take the target feature
features

['TransactionId',
 'BatchId',
 'AccountId',
 'SubscriptionId',
 'CustomerId',
 'CurrencyCode',
 'CountryCode',
 'ProviderId',
 'ProductId',
 'ProductCategory',
 'ChannelId',
 'Amount',
 'Value',
 'TransactionStartTime']

In [9]:
X = training_data[features]
X

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ProductCategory,ChannelId,Amount,Value,TransactionStartTime
0,TransactionId_76871,BatchId_36123,AccountId_3957,SubscriptionId_887,CustomerId_4406,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2018-11-15T02:18:49Z
1,TransactionId_73770,BatchId_15642,AccountId_4841,SubscriptionId_3829,CustomerId_4406,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2018-11-15T02:19:08Z
2,TransactionId_26203,BatchId_53941,AccountId_4229,SubscriptionId_222,CustomerId_4683,UGX,256,ProviderId_6,ProductId_1,airtime,ChannelId_3,500.0,500,2018-11-15T02:44:21Z
3,TransactionId_380,BatchId_102363,AccountId_648,SubscriptionId_2185,CustomerId_988,UGX,256,ProviderId_1,ProductId_21,utility_bill,ChannelId_3,20000.0,21800,2018-11-15T03:32:55Z
4,TransactionId_28195,BatchId_38780,AccountId_4841,SubscriptionId_3829,CustomerId_988,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-644.0,644,2018-11-15T03:34:21Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95657,TransactionId_89881,BatchId_96668,AccountId_4841,SubscriptionId_3829,CustomerId_3078,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-1000.0,1000,2019-02-13T09:54:09Z
95658,TransactionId_91597,BatchId_3503,AccountId_3439,SubscriptionId_2643,CustomerId_3874,UGX,256,ProviderId_6,ProductId_10,airtime,ChannelId_3,1000.0,1000,2019-02-13T09:54:25Z
95659,TransactionId_82501,BatchId_118602,AccountId_4841,SubscriptionId_3829,CustomerId_3874,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-20.0,20,2019-02-13T09:54:35Z
95660,TransactionId_136354,BatchId_70924,AccountId_1346,SubscriptionId_652,CustomerId_1709,UGX,256,ProviderId_6,ProductId_19,tv,ChannelId_3,3000.0,3000,2019-02-13T10:01:10Z
95661,TransactionId_35670,BatchId_29317,AccountId_4841,SubscriptionId_3829,CustomerId_1709,UGX,256,ProviderId_4,ProductId_6,financial_services,ChannelId_2,-60.0,60,2019-02-13T10:01:28Z

In [10]:
train_X, val_X, train_y, val_y = train_test_split(X, y,random_state = 0)

 # Data preprocessing

## dealing with categorical data

In [11]:
s = (train_X.dtypes == 'object')
object_cols = list(s[s].index)
object_cols

['TransactionId',
 'BatchId',
 'AccountId',
 'SubscriptionId',
 'CustomerId',
 'CurrencyCode',
 'ProviderId',
 'ProductId',
 'ProductCategory',
 'ChannelId',
 'TransactionStartTime']

In [12]:
# transform ID columns from TransactionId_76871 to 76871

#train_X.TransactionId.str.split('_')

id_Transaction = train_X.TransactionId.map(lambda col : col.split('_')[1])
train_X.TransactionId = id_Transaction

id_Batch = train_X.BatchId.map(lambda col : col.split('_')[1])
train_X.BatchId = id_Batch

id_Account = train_X.AccountId.map(lambda col : col.split('_')[1])
train_X.AccountId = id_Account

id_Subscription = train_X.SubscriptionId.map(lambda col : col.split('_')[1])
train_X.SubscriptionId = id_Subscription

id_Customer = train_X.CustomerId.map(lambda col : col.split('_')[1])
train_X.CustomerId = id_Customer


id_Provider = train_X.ProviderId.map(lambda col : col.split('_')[1])
train_X.ProviderId = id_Provider

id_Product = train_X.ProductId.map(lambda col : col.split('_')[1])
train_X.ProductId = id_Product

id_Channel = train_X.ChannelId.map(lambda col : col.split('_')[1])
train_X.ChannelId = id_Channel

C:\Users\samaz\anaconda3\lib\site-packages\pandas\core\generic.py:5303: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value

In [13]:
id_Transaction = val_X.TransactionId.map(lambda col : col.split('_')[1])
val_X.TransactionId = id_Transaction

id_Batch = val_X.BatchId.map(lambda col : col.split('_')[1])
val_X.BatchId = id_Batch

id_Account = val_X.AccountId.map(lambda col : col.split('_')[1])
val_X.AccountId = id_Account

id_Subscription = val_X.SubscriptionId.map(lambda col : col.split('_')[1])
val_X.SubscriptionId = id_Subscription

id_Customer = val_X.CustomerId.map(lambda col : col.split('_')[1])
val_X.CustomerId = id_Customer


id_Provider = val_X.ProviderId.map(lambda col : col.split('_')[1])
val_X.ProviderId = id_Provider

id_Product = val_X.ProductId.map(lambda col : col.split('_')[1])
val_X.ProductId = id_Product

id_Channel = val_X.ChannelId.map(lambda col : col.split('_')[1])
val_X.ChannelId = id_Channel

In [14]:
#missing values imputation

cols_with_missing = [col for col in train_X.columns
                     if train_X[col].isnull().any()]
cols_with_missing

#THERE is no missing values yeaay

[]

In [15]:
print(train_X.ProductCategory.unique())
print(train_X.CurrencyCode.unique())
print(val_X.ProductCategory.unique())
print(val_X.CurrencyCode.unique())


print(train_X.CountryCode.unique())
print(val_X.CountryCode.unique())

['data_bundles' 'airtime' 'financial_services' 'movies' 'utility_bill'
 'tv' 'transport' 'ticket' 'other']
['UGX']
['airtime' 'financial_services' 'tv' 'data_bundles' 'movies'
 'utility_bill' 'ticket' 'transport' 'other']
['UGX']
[256]
[256]

Since ProductCategory have 8 possible categorical values, I chose to do One hot encoding for this colums and remove the column CurrencyCode since it has only one possible entry and the same for CountryCode

In [16]:

object_cols = ['ProductCategory']
# Apply one-hot encoder to each column with categorical data
OH_encoder = OneHotEncoder(handle_unknown='ignore', sparse=False)
OH_cols_train = pd.DataFrame(OH_encoder.fit_transform(train_X[object_cols]))
OH_cols_valid = pd.DataFrame(OH_encoder.transform(val_X[object_cols]))

# One-hot encoding removed index; put it back
OH_cols_train.index = train_X.index
OH_cols_valid.index = val_X.index

# Remove categorical columns (will replace with one-hot encoding)
num_X_train = train_X.drop(object_cols, axis=1)
num_X_valid = val_X.drop(object_cols, axis=1)

# Add one-hot encoded columns to numerical features
OH_X_train = pd.concat([num_X_train, OH_cols_train], axis=1)
OH_X_valid = pd.concat([num_X_valid, OH_cols_valid], axis=1)

# Ensure all columns have string type
OH_X_train.columns = OH_X_train.columns.astype(str)
OH_X_valid.columns = OH_X_valid.columns.astype(str)


OH_X_valid

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,CurrencyCode,CountryCode,ProviderId,ProductId,ChannelId,...,TransactionStartTime,0,1,2,3,4,5,6,7,8
69075,91392,117569,834,3759,1179,UGX,256,1,3,3,...,2019-01-23T11:50:31Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
65709,119416,24161,4127,4240,4579,UGX,256,6,10,3,...,2019-01-19T17:11:53Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5430,124012,51521,190,1897,513,UGX,256,6,10,3,...,2018-11-22T06:34:07Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
82375,12251,126898,4840,3829,3212,UGX,256,4,6,2,...,2019-02-01T17:45:07Z,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
60896,27059,17843,1579,821,1956,UGX,256,6,3,3,...,2019-01-15T12:21:53Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91264,33401,50130,1011,928,1362,UGX,256,5,10,3,...,2019-02-08T20:37:34Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4936,127307,119994,3567,3669,4005,UGX,256,5,15,3,...,2018-11-21T09:40:08Z,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
82534,17013,35797,192,433,515,UGX,256,6,10,3,...,2019-02-01T18:44:14Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15412,106649,137004,4249,4429,7343,UGX,256,4,3,2,...,2018-12-04T15:53:32Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9434,117758,115114,4841,3829,2446,UGX,256,4,6,2,...,2018-11-27T17:43:58Z,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [17]:
X_train_reduced = OH_X_train.drop(['CurrencyCode','CountryCode'], axis=1)
X_val_reduced = OH_X_valid.drop(['CurrencyCode','CountryCode'], axis=1)
X_train_reduced

,TransactionId,BatchId,AccountId,SubscriptionId,CustomerId,ProviderId,ProductId,ChannelId,Amount,Value,TransactionStartTime,0,1,2,3,4,5,6,7,8
43878,82059,48408,2946,3991,3371,6,2,3,2500.0,2500,2018-12-28T10:38:00Z,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55031,115282,5122,4468,3787,4928,6,3,3,1000.0,1000,2019-01-09T07:45:47Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28483,36103,117608,3750,3024,4193,6,3,3,2000.0,2000,2018-12-15T15:15:15Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7328,5655,75137,4841,3829,4371,4,6,2,-1000.0,1000,2018-11-24T08:54:26Z,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
18860,87110,84248,4841,3829,2710,4,6,2,-5000.0,5000,2018-12-07T06:39:17Z,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21243,1505,124507,575,4369,912,1,1,3,2000.0,2000,2018-12-08T20:41:20Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45891,68325,94167,4841,3829,2416,4,6,2,-50.0,50,2018-12-29T08:29:15Z,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
42613,62369,85767,571,873,908,6,3,3,1500.0,1500,2018-12-27T17:03:47Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43567,1639,36597,2123,1456,2528,6,1,3,2000.0,2000,2018-12-28T08:06:55Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
68268,83620,99997,2659,3327,3078,6,3,3,1000.0,1000,2019-01-22T15:22:23Z,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [18]:
#deal with the transaction time 

X_train_reduced['TransactionStartTime'] = X_train_reduced['TransactionStartTime'].str.replace('T', ' ')
X_train_reduced['TransactionStartTime'] = X_train_reduced['TransactionStartTime'].str.replace('Z', '')

X_train_reduced['TransactionStartTime'] = pd.to_datetime(X_train_reduced['TransactionStartTime'], infer_datetime_format=True) 

X_train_reduced['Year'] = X_train_reduced['TransactionStartTime'].dt.year
X_train_reduced['Month'] = X_train_reduced['TransactionStartTime'].dt.month
X_train_reduced['Day'] = X_train_reduced['TransactionStartTime'].dt.day
X_train_reduced['Hour'] = X_train_reduced['TransactionStartTime'].dt.hour
X_train_reduced['Minute'] = X_train_reduced['TransactionStartTime'].dt.minute
X_train_reduced['Seconds'] = X_train_reduced['TransactionStartTime'].dt.second
X_train_reduced['week'] = X_train_reduced['TransactionStartTime'].dt.week
X_train_reduced['weekday'] = X_train_reduced['TransactionStartTime'].dt.weekday


X_val_reduced['TransactionStartTime'] = X_val_reduced['TransactionStartTime'].str.replace('T', ' ')
X_val_reduced['TransactionStartTime'] = X_val_reduced['TransactionStartTime'].str.replace('Z', '')

X_val_reduced['TransactionStartTime'] = pd.to_datetime(X_val_reduced['TransactionStartTime'], infer_datetime_format=True) 

X_val_reduced['Year'] = X_val_reduced['TransactionStartTime'].dt.year
X_val_reduced['Month'] = X_val_reduced['TransactionStartTime'].dt.month
X_val_reduced['Day'] = X_val_reduced['TransactionStartTime'].dt.day
X_val_reduced['Hour'] = X_val_reduced['TransactionStartTime'].dt.hour
X_val_reduced['Minute'] = X_val_reduced['TransactionStartTime'].dt.minute
X_val_reduced['Seconds'] = X_val_reduced['TransactionStartTime'].dt.second
X_val_reduced['week'] = X_val_reduced['TransactionStartTime'].dt.week
X_val_reduced['weekday'] = X_val_reduced['TransactionStartTime'].dt.weekday

In [22]:
#now that we seperated the colums TransactionStartTime we need to drop it
X_train_reduced = OH_X_train.drop(['TransactionStartTime'], axis=1)
X_val_reduced = OH_X_valid.drop(['TransactionStartTime'], axis=1)

Index(['TransactionId', 'BatchId', 'AccountId', 'SubscriptionId', 'CustomerId',
       'ProviderId', 'ProductId', 'ChannelId', 'Amount', 'Value',
       'TransactionStartTime', '0', '1', '2', '3', '4', '5', '6', '7', '8',
       'Year', 'Month', 'Day', 'Hour', 'Minute', 'Seconds', 'week', 'weekday'],
      dtype='object')

##### Features engineering

## Models

### Random Forest Regressor

In [20]:
def forest_model(train_X,train_y,val_X,val_y):
    model = RandomForestRegressor(random_state=1)
    model.fit(train_X, train_y)
    preds = model.predict(val_X)
    return(mean_absolute_error(val_y, preds))

In [21]:
forest_model(X_train_reduced,train_y,X_val_reduced,val_y)

TypeError: float() argument must be a string or a number, not 'Timestamp'